spring.application.name=botanix
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/botanicax}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:botanix.soporte@gmail.com}
spring.mail.password=${MAIL_PASSWORD:akfk vydi aaur bmkv}
spring.mail.test-connection=${MAIL_TEST_CONNECTION:false}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SMTP_SSL_ENABLE:false}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT:10000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_WRITE_TIMEOUT:10000}
spring.mail.properties.mail.debug=${MAIL_DEBUG:false}
